Imports System.Net
Imports System.Net.Mail
Imports System.Web.Optimization
Imports System.Web.Http
Imports System.Web.Routing

Public Class Global_asax
    Inherits HttpApplication

    Sub Application_Start(sender As Object, e As EventArgs)
        ' Fires when the application is started
        RouteConfig.RegisterRoutes(RouteTable.Routes)
        BundleConfig.RegisterBundles(BundleTable.Bundles)
        GlobalConfiguration.Configure(AddressOf WebApiConfig.Register)
    End Sub

    Sub Application_Error(ByVal sender As Object, ByVal e As EventArgs)
        ' Code that runs when an unhandled error occurs

        ' Get the exception object.
        Dim exc As Exception = Server.GetLastError

        ' Handle HTTP errors (avoid trapping HttpUnhandledException
        ' which is generated when a non-HTTP exception 
        ' such as the ones generated by buttons 1-3 in 
        ' Default.aspx is not handled at the page level).
        'If (exc.GetType Is GetType(HttpException)) Then
        '    ' The Complete Error Handling Example generates
        '    ' some errors using URLs with "NoCatch" in them;
        '    ' ignore these here to simulate what would happen
        '    ' if a global.asax handler were not implemented.
        '    If exc.Message.Contains("NoCatch") Or exc.Message.Contains("maxUrlLength") Then
        '        Return
        '    End If

        '    'Redirect HTTP errors to HttpError page
        '    Server.Transfer("HttpErrorPage.aspx")
        'End If

        ' For other kinds of errors give the user some information
        ' but stay on the default page


        ' Log the exception and notify system operators

        Dim Smtp_Server As New SmtpClient("SMTP.1AND1.COM")
        Dim e_mail As New MailMessage()
        Smtp_Server.UseDefaultCredentials = False

        Smtp_Server.Credentials = New NetworkCredential("test@invosupport.com", "Invotech9800")

        Smtp_Server.EnableSsl = True

        e_mail = New MailMessage()

        e_mail.From = New MailAddress("licensing@invosupport.com")

        'pending translation
        e_mail.Body = exc.ToString
        e_mail.Body &= vbCrLf
        e_mail.Body &= vbCrLf

        ' e_mail.Body &= Session("UserNo")
        e_mail.Subject = "InvoTech Licensing Error"
        e_mail.IsBodyHtml = False

        e_mail.To.Add(ConfigurationManager.AppSettings("errorrecipients"))
        Smtp_Server.Send(e_mail)

        ' Clear the error from the server
        Server.ClearError()

        Server.Transfer("~\ErrorPage\error.aspx")
    End Sub
End Class