'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class KeyGen
    
    '''<summary>
    '''lblLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DropDownListEmpLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListEmpLimit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DropDownListInvLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListInvLimit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkboxHandheld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxHandheld As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''combosledLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combosledLimit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkboxHR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxHR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxRFID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxRFID As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxMulti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxMulti As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtMulti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMulti As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkboxLaundryInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxLaundryInterface As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxCrown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxCrown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxGIMSLaundry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxGIMSLaundry As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxExpires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxExpires As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtExpire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpire As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkboxWhiteUpick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxWhiteUpick As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxPhoenix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxPhoenix As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxSRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxSRS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxWhiteConveyor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxWhiteConveyor As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxAutoValet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxAutoValet As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxHiemac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxHiemac As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxSRSConveyorAUDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxSRSConveyorAUDS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxEventUniforms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxEventUniforms As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxITPasswords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxITPasswords As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxMetalProgretti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxMetalProgretti As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxAccounting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxAccounting As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxMMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxMMS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxDemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxDemo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxRestricted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxRestricted As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxCoatcheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxCoatcheck As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxOneforOneScrubs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxOneforOneScrubs As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxWhiteBiometric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxWhiteBiometric As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxWhiteSortingConveyorsConveyor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxWhiteSortingConveyorsConveyor As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxMPCommonEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxMPCommonEmployees As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxSelfIssueStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxSelfIssueStation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxSelfIssuePortal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxSelfIssuePortal As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxInventoryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxInventoryLimit As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxEmployeeLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxEmployeeLimit As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxPolytex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxPolytex As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxLaundryExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxLaundryExport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxCruiseCrewsExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxCruiseCrewsExport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxFornet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxFornet As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkboxACS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkboxACS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''IsConnected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsConnected As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''IsDisconnected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsDisconnected As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''TextBoxIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxIP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLicense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLicense As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelValidation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnGenerate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValidate As Global.System.Web.UI.WebControls.Button
End Class
